version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/equed-core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "composer"
    directory: "/equed-lms"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "composer"
    directory: "/equed-cert"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "composer"
    directory: "/equed-qms"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "composer"
    directory: "/equed-center"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "composer"
    directory: "/equed-instructor"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "composer"
    directory: "/equed-admin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "npm"
    directory: "/equed-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
