<?php

declare(strict_types=1);

return [
    'ctrl' => [
        'title' => 'LLL:EXT:equed_lms/Resources/Private/Language/locallang_db.xlf:tx_equedlms_domain_model_submissionreview',
        'label' => 'status',
        'tstamp' => 'tstamp',
        'crdate' => 'crdate',
        'delete' => 'deleted',
        'iconfile' => 'EXT:equed_lms/Resources/Public/Icons/badge.svg'
    ],
    'columns' => [
        'submission' => [
            'label' => 'Submission',
            'config' => [
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_equedlms_domain_model_usersubmission',
                'size' => 1,
                'maxitems' => 1
            ]
        ],
        'reviewed_by' => [
            'label' => 'Reviewed by',
            'config' => [
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'fe_users',
                'size' => 1,
                'maxitems' => 1
            ]
        ],
        'status' => [
            'label' => 'Status',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'items' => [
                    ['Open', \Equed\EquedLms\Enum\SubmissionReviewStatus::Open->value],
                    ['Approved', \Equed\EquedLms\Enum\SubmissionReviewStatus::Approved->value],
                    ['Rejected', \Equed\EquedLms\Enum\SubmissionReviewStatus::Rejected->value],
                ],
                'default' => \Equed\EquedLms\Enum\SubmissionReviewStatus::Open->value
            ]
        ],
        'comment' => [
            'label' => 'Comment',
            'config' => [
                'type' => 'text',
                'enableRichtext' => true
            ]
        ],
        'evaluation_document' => [
            'label' => 'Evaluation Document',
            'config' => [
                'type' => 'file',
                'maxitems' => 1
            ]
        ],
        'visible_for_user' => [
            'label' => 'Visible for User',
            'config' => [
                'type' => 'check',
                'default' => 0
            ]
        ],
        'was_generated_by_gpt' => [
            'label' => 'Generated by GPT',
            'config' => [
                'type' => 'check',
                'default' => 0
            ]
        ],
        'lang' => [
            'label' => 'Language',
            'config' => [
                'type' => 'input',
                'eval' => 'trim'
            ]
        ]
    ],
    'types' => [
        '0' => ['showitem' => 'submission, reviewed_by, status, comment, evaluation_document, visible_for_user, was_generated_by_gpt, lang']
    ]
];
