parameters:
  equed_lms.training_record_output_path: '%kernel.project_dir%/var/training_records'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Equed\EquedLms\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/**'

  # Translation service with fallback logic registered for DI
  Equed\EquedLms\Service\GptTranslationService:
    public: true

  Equed\EquedLms\Service\Translator: ~

  Equed\EquedLms\Domain\Service\TranslatorInterface:
    class: Equed\EquedLms\Service\Translator

  # LanguageService now injected with GptTranslationService
  Equed\EquedLms\Service\LanguageService:
    arguments:
      $gptTranslationService: '@Equed\EquedLms\Service\GptTranslationService'
      $translator: '@Equed\EquedLms\Service\Translator'

  # Event listener for course completion (PSR-14)
  Equed\EquedLms\EventListener\CourseCompletedListener:
    tags:
      - { name: 'event.listener', identifier: 'equed.course.completed' }

  # Custom validator for lesson submissions
  Equed\EquedLms\Validation\LessonSubmissionValidator:
    tags:
      - { name: 'validation.validator' }

  # Middleware to check submissions before processing
  Equed\EquedLms\Middleware\SubmissionCheckMiddleware:
    tags:
      - { name: 'middleware', priority: 50 }

  # Register Doctrine schema loader
  Equed\EquedLms\EventListener\SchemaLoader:
    tags:
      - { name: 'event.listener' }

  Equed\EquedLms\Domain\Repository\FrontendUserRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\FrontendUserRepository

  Equed\EquedLms\Domain\Repository\UserProfileRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserProfileRepository

  Equed\EquedLms\Domain\Repository\UserBadgeRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserBadgeRepository

  Equed\EquedLms\Domain\Repository\BadgeAwardRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\BadgeAwardRepository

  Equed\EquedLms\Domain\Repository\CourseGoalRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\CourseGoalRepository

  Equed\EquedLms\Domain\Repository\LessonAttemptRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\LessonAttemptRepository

  Equed\EquedLms\Domain\Repository\LessonRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\LessonRepository

  Equed\EquedLms\Domain\Repository\LearningPathRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\LearningPathRepository

  Equed\EquedLms\Domain\Service\DashboardServiceInterface:
    class: Equed\EquedLms\Service\DashboardService

  Equed\EquedLms\Domain\Service\CourseCompletionServiceInterface:
    class: Equed\EquedLms\Service\CourseCompletionService

  Equed\EquedLms\Domain\Service\MediaUploadServiceInterface:
    class: Equed\EquedLms\Service\MediaUploadService

  Equed\EquedLms\Domain\Service\DocumentServiceInterface:
    class: Equed\EquedLms\Service\DocumentService

  Equed\EquedLms\Domain\Service\LanguageServiceInterface:
    class: Equed\EquedLms\Service\LanguageService

  Equed\EquedLms\Domain\Service\ClockInterface:
    class: Equed\EquedLms\Service\SystemClock
  Equed\EquedLms\Domain\Repository\CourseInstanceRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\CourseInstanceRepository

  Equed\EquedLms\Domain\Repository\LessonProgressRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\LessonProgressRepository

  Equed\EquedLms\Domain\Repository\NotificationRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\NotificationRepository

  Equed\EquedLms\Domain\Repository\UserCourseRecordRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserCourseRecordRepository

  Equed\EquedLms\Domain\Repository\UserSubmissionRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserSubmissionRepository

  Equed\EquedLms\Domain\Repository\CertificateDispatchRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\CertificateDispatchRepository

  Equed\EquedLms\Domain\Repository\SubmissionRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\SubmissionRepository

  Equed\EquedLms\Factory\FrontendUserFactoryInterface:
    class: Equed\EquedLms\Factory\DefaultFrontendUserFactory

  Equed\EquedLms\Factory\UserCourseRecordFactoryInterface:
    class: Equed\EquedLms\Factory\DefaultUserCourseRecordFactory

  Equed\EquedLms\Domain\Service\JwtServiceInterface:
    class: Equed\EquedLms\Service\JwtService
    arguments:
      $clock: '@Equed\EquedLms\Domain\Service\ClockInterface'

  Equed\EquedLms\Domain\Service\NotificationServiceInterface:
    class: Equed\EquedLms\Service\NotificationService

  Equed\EquedLms\Domain\Service\CourseGoalServiceInterface:
    class: Equed\EquedLms\Service\CourseGoalService

  Equed\EquedLms\Domain\Service\TrainingRecordGeneratorInterface:
    class: Equed\EquedLms\Service\TrainingRecordGeneratorService

  Equed\EquedLms\Service\TrainingRecordGeneratorService:
    arguments:
      $outputDirectory: '%equed_lms.training_record_output_path%'

  Equed\EquedLms\Domain\Service\ExamNotificationServiceInterface:
    class: Equed\EquedLms\Service\ExamNotificationService

  Equed\EquedLms\Service\ProgressServiceInterface:
    class: Equed\EquedLms\Service\ProgressService

  Equed\EquedLms\Service\MailServiceInterface:
    class: Equed\EquedLms\Service\Email\MailService

