parameters:
  equed_lms.training_record_output_path: '%kernel.project_dir%/var/training_records'
  equed_lms.max_upload_size: 5242880

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Equed\EquedLms\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/**'

  # Translation service with fallback logic registered for DI
  Equed\EquedLms\Service\GptTranslationService:
    public: true

  Equed\EquedLms\Service\Translator: ~

  Equed\EquedLms\Domain\Service\TranslatorInterface:
    class: Equed\EquedLms\Service\Translator

  # LanguageService now injected with GptTranslationService
  Equed\EquedLms\Service\LanguageService:
    arguments:
      $gptTranslationService: '@Equed\EquedLms\Service\GptTranslationService'
      $translator: '@Equed\EquedLms\Service\Translator'

  # Event listener for course completion (PSR-14)
  Equed\EquedLms\EventListener\CourseCompletedListener:
    tags:
      - { name: 'event.listener', identifier: 'equed.course.completed' }

  # Custom validator for lesson submissions
  Equed\EquedLms\Validation\LessonSubmissionValidator:
    tags:
      - { name: 'validation.validator' }

  # Middleware to check submissions before processing
  Equed\EquedLms\Middleware\SubmissionCheckMiddleware:
    tags:
      - { name: 'middleware', priority: 50 }

  # Register Doctrine schema loader
  Equed\EquedLms\EventListener\SchemaLoader:
    tags:
      - { name: 'event.listener' }

  Equed\EquedLms\Domain\Repository\FrontendUserRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\FrontendUserRepository

  Equed\EquedLms\Domain\Repository\UserProfileRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserProfileRepository

  Equed\EquedLms\Domain\Repository\UserBadgeRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserBadgeRepository

  Equed\EquedLms\Domain\Repository\BadgeAwardRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\BadgeAwardRepository

  Equed\EquedLms\Domain\Repository\CourseGoalRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\CourseGoalRepository

  Equed\EquedLms\Domain\Repository\LessonAttemptRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\LessonAttemptRepository

  Equed\EquedLms\Domain\Repository\LessonRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\LessonRepository

  Equed\EquedLms\Domain\Repository\LearningPathRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\LearningPathRepository

  Equed\EquedLms\Domain\Service\DashboardServiceInterface:
    class: Equed\EquedLms\Service\DashboardService

  Equed\EquedLms\Domain\Service\CourseCompletionServiceInterface:
    class: Equed\EquedLms\Service\CourseCompletionService

  Equed\EquedLms\Domain\Service\MediaUploadServiceInterface:
    class: Equed\EquedLms\Service\MediaUploadService
    arguments:
      $maxFileSize: '%equed_lms.max_upload_size%'

  Equed\EquedLms\Domain\Service\DocumentServiceInterface:
    class: Equed\EquedLms\Service\DocumentService

  Equed\EquedLms\Domain\Service\InstructorServiceInterface:
    class: Equed\EquedLms\Service\InstructorService

  Equed\EquedLms\Domain\Service\UserAccessServiceInterface:
    class: Equed\EquedLms\Service\UserAccessService

  Equed\EquedLms\Domain\Service\LanguageServiceInterface:
    class: Equed\EquedLms\Service\LanguageService

  Equed\EquedLms\Domain\Service\ClockInterface:
    class: Equed\EquedLms\Service\SystemClock
  Equed\EquedLms\Domain\Service\FileReaderInterface:
    class: Equed\EquedLms\Service\LocalFileReader
  Equed\EquedLms\Domain\Repository\CourseInstanceRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\CourseInstanceRepository

  Equed\EquedLms\Domain\Repository\LessonProgressRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\LessonProgressRepository

  Equed\EquedLms\Domain\Repository\NotificationRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\NotificationRepository

  Equed\EquedLms\Domain\Repository\UserCourseRecordRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserCourseRecordRepository

  Equed\EquedLms\Domain\Repository\UserSubmissionRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserSubmissionRepository

  Equed\EquedLms\Domain\Repository\CertificateDispatchRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\CertificateDispatchRepository

  Equed\EquedLms\Domain\Repository\SubmissionRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\SubmissionRepository

  Equed\EquedLms\Domain\Repository\InstructorFeedbackRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\InstructorFeedbackRepository

  Equed\EquedLms\Domain\Repository\GlossaryEntryRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\GlossaryEntryRepository

  Equed\EquedLms\Domain\Repository\CourseProgramRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\CourseProgramRepository

  Equed\EquedLms\Domain\Repository\CourseBundleRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\CourseBundleRepository

  Equed\EquedLms\Domain\Repository\CourseAccessMapRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\CourseAccessMapRepository

  Equed\EquedLms\Domain\Repository\MaterialRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\MaterialRepository

  Equed\EquedLms\Domain\Repository\QmsCaseRecordRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\QmsCaseRecordRepository

  Equed\EquedLms\Factory\FrontendUserFactoryInterface:
    class: Equed\EquedLms\Factory\DefaultFrontendUserFactory

  Equed\EquedLms\Factory\UserCourseRecordFactoryInterface:
    class: Equed\EquedLms\Factory\DefaultUserCourseRecordFactory

  Equed\EquedLms\Domain\Service\UserAccountServiceInterface:
    class: Equed\EquedLms\Service\UserAccountService

  Equed\EquedLms\Domain\Service\JwtServiceInterface:
    class: Equed\EquedLms\Service\JwtService
    arguments:
      $clock: '@Equed\EquedLms\Domain\Service\ClockInterface'

  Equed\EquedLms\Domain\Service\AuthenticationServiceInterface:
    class: Equed\EquedLms\Service\AuthenticationService

  Equed\EquedLms\Domain\Service\NotificationServiceInterface:
    class: Equed\EquedLms\Service\NotificationService

  Equed\EquedLms\Domain\Service\CourseGoalServiceInterface:
    class: Equed\EquedLms\Service\CourseGoalService

  Equed\EquedLms\Domain\Service\TrainingRecordGeneratorInterface:
    class: Equed\EquedLms\Service\TrainingRecordGeneratorService

  Equed\EquedLms\Service\TrainingRecordGeneratorService:
    arguments:
      $outputDirectory: '%equed_lms.training_record_output_path%'

  Equed\EquedLms\Domain\Service\ExamNotificationServiceInterface:
    class: Equed\EquedLms\Service\ExamNotificationService

  Equed\EquedLms\Domain\Service\ExamServiceInterface:
    class: Equed\EquedLms\Service\ExamService

  Equed\EquedLms\Service\ExamService:
    arguments:
      $templateBasePath: '@=service("Equed\\\\EquedLms\\\\Service\\\\SettingsService").get("examTemplatePath")'

  Equed\EquedLms\Domain\Service\LessonProgressServiceInterface:
    class: Equed\EquedLms\Service\LessonProgressService

  Equed\EquedLms\Service\CourseProgressServiceInterface:
    class: Equed\EquedLms\Service\CourseProgressService

  Equed\EquedLms\Service\ProgressServiceInterface:
    class: Equed\EquedLms\Service\ProgressService

  Equed\EquedLms\Domain\Service\UserCourseRecordCrudServiceInterface:
    class: Equed\EquedLms\Service\UserCourseRecordCrudService

  Equed\EquedLms\Service\SubmissionService:
    arguments:
      $clock: '@Equed\EquedLms\Domain\Service\ClockInterface'

  Equed\EquedLms\Service\QmsApiService:
    arguments:
      $clock: '@Equed\EquedLms\Domain\Service\ClockInterface'
      $repository: '@Equed\EquedLms\Domain\Repository\QmsCaseRecordRepositoryInterface'

  Equed\EquedLms\Service\ServiceCenterCaseService:
    arguments:
      $repository: '@Equed\EquedLms\Domain\Repository\QmsCaseRecordRepositoryInterface'

  Equed\EquedLms\Service\UserAccountService:
    arguments:
      $clock: '@Equed\EquedLms\Domain\Service\ClockInterface'

  Equed\EquedLms\Service\UserCourseRecordCrudService:
    arguments:
      $clock: '@Equed\EquedLms\Domain\Service\ClockInterface'

  Equed\EquedLms\Service\MailServiceInterface:
    class: Equed\EquedLms\Service\Email\MailService

  Equed\EquedLms\Domain\Service\MaterialListServiceInterface:
    class: Equed\EquedLms\Service\MaterialListService

  Equed\EquedLms\Domain\Service\MaterialServiceInterface:
    class: Equed\EquedLms\Service\MaterialService

  Equed\EquedLms\Service\QuizManagerInterface:
    class: Equed\EquedLms\Service\QuizManager

  Equed\EquedLms\Domain\Service\CourseBundleServiceInterface:
    class: Equed\EquedLms\Service\CourseBundleService

  Equed\EquedLms\Service\InstructorService:
    arguments:
      $clock: '@Equed\EquedLms\Domain\Service\ClockInterface'

  Equed\EquedLms\Domain\Service\CourseOverviewServiceInterface:
    class: Equed\EquedLms\Service\CourseOverviewService
    arguments:
      $clock: '@Equed\EquedLms\Domain\Service\ClockInterface'
