services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Equed\EquedLms\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/**'

  # Translation service with fallback logic registered for DI
  Equed\EquedLms\Service\GptTranslationService:
    public: true

  # LanguageService now injected with GptTranslationService
  Equed\EquedLms\Service\LanguageService:
    arguments:
      $gptTranslationService: '@Equed\EquedLms\Service\GptTranslationService'

  # Event listener for course completion (PSR-14)
  Equed\EquedLms\EventListener\CourseCompletedListener:
    tags:
      - { name: 'event.listener', identifier: 'equed.course.completed' }

  # Custom validator for lesson submissions
  Equed\EquedLms\Validation\LessonSubmissionValidator:
    tags:
      - { name: 'validation.validator' }

  # Middleware to check submissions before processing
  Equed\EquedLms\Middleware\SubmissionCheckMiddleware:
    tags:
      - { name: 'middleware', priority: 50 }

  # Register Doctrine schema loader
  Equed\EquedLms\EventListener\SchemaLoader:
    tags:
      - { name: 'event.listener' }

  Equed\EquedLms\Domain\Repository\FrontendUserRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\FrontendUserRepository

  Equed\EquedLms\Domain\Repository\UserProfileRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserProfileRepository

  Equed\EquedLms\Domain\Repository\UserBadgeRepositoryInterface:
    class: Equed\EquedLms\Domain\Repository\UserBadgeRepository

  Equed\EquedLms\Domain\Service\DashboardServiceInterface:
    class: Equed\EquedLms\Service\DashboardService

  Equed\EquedLms\Domain\Service\CourseCompletionServiceInterface:
    class: Equed\EquedLms\Service\CourseCompletionService

  Equed\EquedLms\Domain\Service\MediaUploadServiceInterface:
    class: Equed\EquedLms\Service\MediaUploadService

  Equed\EquedLms\Domain\Service\DocumentServiceInterface:
    class: Equed\EquedLms\Service\DocumentService

  Equed\EquedLms\Domain\Service\ClockInterface:
    class: Equed\EquedLms\Service\SystemClock
