name: Monorepo Composer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Validate extension composer files
        run: |
          # Iterate over all directories in the repository root that start with "equed-"
          for dir in equed-*; do
            # Only proceed if the path is a directory
            [ -d "$dir" ] || continue

            # Check whether a composer.json exists in the directory
            if [ -f "$dir/composer.json" ]; then
              echo "🔍 Validating $dir..."

              # Run composer validate without --strict so warnings do not fail the build
              if composer validate --working-dir "$dir"; then
                echo "✔ $dir/composer.json is valid"
              else
                echo "❌ Validation failed in $dir"
                exit 1
              fi
            else
              echo "ℹ️  Skipping $dir – no composer.json found"
            fi
          done
