name: Monorepo Integrity Check

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Composer validate
        run: |
          for dir in equed-*; do
            if [ -f "$dir/composer.json" ]; then
              composer validate --strict --working-dir "$dir"
            fi
          done
