name: Monorepo Integrity Check

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Composer validate
        run: composer validate --strict
      - name: Additional structure check
        run: |
          if [ -x ./scripts/check-monorepo-structure.sh ]; then
            ./scripts/check-monorepo-structure.sh
          else
            echo 'No monorepo structure script found'
          fi
