name: Security Audit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Run Composer audit
        run: |
          for dir in equed-*; do
            if [ -f "$dir/composer.lock" ]; then
              echo "Auditing $dir"
              composer audit --working-dir "$dir"
            else
              echo "Skipping $dir: composer.lock not found"
            fi
          done
