name: Translation Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xml, gd
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Synchronize translations
        run: vendor/bin/typo3 translation:sync
